version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./config/prometheus/etc/prometheus/:/etc/prometheus/
      - ./config/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    user: root

  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - './config/mysql/data:/var/lib/mysql'
      - './config/mysql/ops/database:/docker-entrypoint-initdb.d'
      - './config/mysql/log:/var/log/mysql'

  mysqld_exporter:
    image: prom/mysqld-exporter:v0.14.0
    user: root
    ports:
      - '9104:9104'
    links:
      - mysql
    environment:
      - 'DATA_SOURCE_NAME=root:password@(mysql:3306)/db'
      - 'collect.info_schema.tablestats=true'
      - 'collect.info_schema.userstats=true'
      - 'collect.info_schema.query_response_time=true'
      - 'collect.auto_increment.columns=true'
      - 'collect.perf_schema.tableiowaits=true'
      - 'collect.perf_schema.tablelocks=true'
    depends_on:
      - mysql

  cortex:
    image: cortexproject/cortex:v0.1.0
    ports:
      - '9009:9009'
    command:
      - '-config.file=/etc/single-process-config.yaml'
      - '-log.level=debug'
    depends_on:
      - prometheus
    volumes:
      - './config/cortex/single-process-config.yaml:/etc/single-process-config.yaml'

  grafana:
    image: grafana/grafana:9.0.2
    ports:
      - '3000:3000'
    volumes:
      - './config/grafana/grafana_data:/var/lib/grafana'
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    user: root

  alertmanager:
    image: prom/alertmanager:v0.24.0
    ports:
      - '9093:9093'
    volumes:
      - './etc/prometheus/alertmanager/:/etc/alertmanager/'
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
